import os

DOCS = {
    "annual-leave-policy.txt": """EnterpriseCorp Annual Leave Policy
All full-time employees at EnterpriseCorp are entitled to 20 days of paid annual leave per calendar year, accrued at a rate of 1.66 days per month. Part-time employees accrue annual leave on a pro-rata basis corresponding to their contracted hours. Employees may carry over a maximum of 5 unused annual leave days into the following calendar year. Any additional unused days beyond this limit will be forfeited on December 31st. Employees must submit leave requests through the HR portal at least 14 days in advance for absences exceeding 3 consecutive business days. For requests of 1 to 3 days, a minimum of 48 hours notice is required. Line managers are required to review and respond to all leave requests within 3 business days of submission. In the event of conflicting leave requests within the same department, priority will be granted based on the date of submission and critical project deadlines. Leave requests during the company designated blackout period, which occurs annually between December 15th and December 31st, require exceptional approval from the Department Director. Upon voluntary or involuntary termination of employment, employees will be compensated for accrued but unused annual leave days in their final paycheck at their standard daily base rate.""",

    "maternity-leave-policy.txt": """EnterpriseCorp Maternity Leave Policy
EnterpriseCorp provides 26 weeks of fully paid maternity leave to female employees welcoming a child through birth or adoption. To be eligible for the full 26 weeks of paid leave, the employee must have completed a minimum of 12 consecutive months of continuous employment at EnterpriseCorp prior to the expected date of delivery or adoption placement. Employees with less than 12 months of tenure are eligible for 12 weeks of paid leave and an additional 14 weeks of unpaid leave. Expectant mothers may commence their maternity leave up to 8 weeks prior to their expected delivery date. Employees must notify the HR department and their direct manager of their intention to take maternity leave at least 15 weeks prior to the expected start date, accompanied by a medical certificate or relevant adoption documentation. During the paid maternity leave period, employees will continue to receive their standard base salary, and all company benefits, including health insurance and provident fund contributions, will remain active. Following the conclusion of the 26-week leave period, employees have the option to request an additional 12 weeks of unpaid extended leave, subject to managerial approval based on operational requirements. Returning mothers are entitled to flexible working hours, including a gradual return-to-work schedule consisting of a 4-day work week for the first month at full pay.""",

    "paternity-leave-policy.txt": """EnterpriseCorp Paternity Leave Policy
EnterpriseCorp grants 4 weeks of fully paid paternity leave to eligible male employees following the birth or adoption of a child. This policy applies to all full-time employees who are the biological father or the legally recognized adoptive parent of the child, provided they have completed a minimum of 6 months of continuous service with the company. Employees with less than 6 months of service are entitled to 2 weeks of paid paternity leave. Paternity leave must be taken within the first 6 months following the child birth or adoption placement. The leave can be taken consecutively as a 4-week block or split into two separate 2-week blocks. Employees must formally apply for paternity leave through the HR portal at least 8 weeks prior to the expected delivery or adoption date, acknowledging that actual dates may shift. In instances of premature birth or medical emergencies, the advance notice requirement is waived, but employees must notify HR within 48 hours of the event. During paternity leave, the employee base salary and all benefits, including health coverage and pension accrual, remain fully intact. Unused paternity leave cannot be cashed out, transferred to another individual, or carried over beyond the 6-month eligibility window.""",

    "remote-work-policy.txt": """EnterpriseCorp Remote Work Policy
EnterpriseCorp operates on a hybrid work model, allowing eligible employees to work remotely for up to 3 days per calendar week. To qualify for remote work, employees must have successfully completed their 90-day probationary period and maintain a performance rating of Meets Expectations or higher. Remote work days must be scheduled in agreement with the employee direct manager at the beginning of each quarter to ensure adequate in-office coverage across all departments. Core collaboration days are designated as Tuesdays and Thursdays; all employees are required to be physically present in the office on these days unless on approved leave or business travel. While working remotely, employees must be online and accessible via company communication channels during the core operational hours of 10:00 AM to 3:00 PM local time. Employees are responsible for securing a reliable internet connection with a minimum download speed of 50 Mbps and a private, distraction-free workspace. EnterpriseCorp provides a one-time home office setup stipend of $500 for the purchase of ergonomic furniture or approved peripherals. The company reserves the right to suspend or revoke remote work privileges if an employee productivity declines, if communication protocols are ignored, or if project requirements demand full-time on-site presence.""",

    "code-of-conduct-policy.txt": """EnterpriseCorp Code of Conduct Policy
The EnterpriseCorp Code of Conduct establishes the baseline expectations for professional behavior for all employees, contractors, and temporary staff. Employees must treat colleagues, clients, and vendors with respect, strictly prohibiting any form of discrimination, harassment, or bullying based on race, gender, age, religion, sexual orientation, or disability. Any observed or experienced violations must be reported immediately to the HR department or through the anonymous internal whistleblower hotline. Employees must avoid conflicts of interest, defined as situations where personal, financial, or familial relationships could improperly influence business decisions. Any potential conflict of interest, including secondary employment or consulting work, must be disclosed in writing to the Compliance Officer within 5 business days of the conflict arising. The acceptance of gifts, entertainment, or hospitality from clients or vendors is limited to items with a verifiable market value of less than $100 per calendar year from a single source. Furthermore, employees must protect the company intellectual property, utilizing confidential information solely for authorized business purposes. Violations of this Code of Conduct will result in disciplinary action, which may progress from formal written warnings to immediate termination of employment, depending on the severity and nature of the infraction.""",

    "attendance-and-working-hours-policy.txt": """EnterpriseCorp Attendance and Working Hours Policy
The standard work week at EnterpriseCorp consists of 40 hours, scheduled from Monday to Friday. Standard office hours are 9:00 AM to 5:00 PM, which includes a mandatory 1-hour unpaid lunch break to be taken between 12:00 PM and 2:00 PM. Employees are expected to arrive on time and be prepared to commence work at their scheduled start time. Tardiness of more than 15 minutes must be reported to the direct manager via the internal communication platform prior to the start of the shift. An employee who accumulates three undocumented late arrivals within a single 30-day period will receive a formal verbal warning. Unplanned absences due to illness or personal emergencies must be communicated to the direct manager and HR no later than 9:30 AM on the day of the absence. Failure to report an absence for three consecutive business days will be considered job abandonment and may result in immediate termination of employment. Non-exempt employees who are requested by their manager to work beyond 40 hours in a single work week will be compensated at a rate of 1.5 times their regular hourly wage for the overtime hours, requiring prior written approval from the department head.""",

    "password-and-authentication-policy.txt": """EnterpriseCorp Password and Authentication Policy
All employees must adhere to strict password protocols to safeguard EnterpriseCorp networks, applications, and sensitive data. User account passwords must contain a minimum of 14 characters and include at least one uppercase letter, one lowercase letter, one numerical digit, and one special character. Passwords must not contain the user name, employee ID, company name, or common dictionary words. The IT department enforces mandatory password expiration every 90 days. Upon expiration, employees cannot reuse any of their previous 5 passwords. Multi-Factor Authentication is deployed universally across all internal and cloud-based systems; employees are required to verify their identity using the company-approved authenticator application installed on their registered mobile device. Physical security keys are issued to system administrators and employees handling Tier 1 restricted data. Account lockouts will automatically occur after 5 consecutive failed login attempts within a 15-minute window. Locked accounts require a manual reset via the IT Service Desk and identity verification using an employee badge or verified alternate email. Writing down passwords on physical notes or storing them in unencrypted digital files is strictly prohibited and constitutes a severe security violation subject to formal disciplinary proceedings.""",

    "acceptable-device-usage-policy.txt": """EnterpriseCorp Acceptable Device Usage Policy
EnterpriseCorp provides employees with company-owned laptops, mobile devices, and peripherals necessary to fulfill their job responsibilities. These devices remain the exclusive property of the company and are intended primarily for business use. Incidental personal use is permitted provided it does not interfere with productivity, consume excessive network bandwidth, or violate the Code of Conduct. Employees are strictly prohibited from using company devices to access, download, or distribute illegal content, unauthorized peer-to-peer file-sharing platforms, or online gambling services. Users must not attempt to bypass local administrative restrictions, disable pre-installed security software, or alter endpoint management configurations. All devices are monitored for security and compliance purposes; employees should have no expectation of privacy regarding any data, communications, or browsing history generated on company equipment. In the event a device is lost, stolen, or damaged, the employee must report the incident to the IT Service Desk within 4 hours to initiate remote data wipe protocols. Upon termination of employment, all hardware must be returned to the IT department within 3 business days. Failure to return equipment will result in the depreciated cost of the hardware being deducted from the employee final salary settlement.""",

    "data-security-and-classification-policy.txt": """EnterpriseCorp Data Security and Classification Policy
To protect corporate and client information, EnterpriseCorp mandates the strict classification and handling of all digital and physical data. Data is categorized into three tiers: Public, Internal, and Restricted. Public data is approved for external distribution. Internal data includes standard operational communications and unreleased marketing materials, which may not be shared outside the company without managerial consent. Restricted data encompasses personally identifiable information, financial records, client databases, and proprietary source code. Access to Restricted data is granted strictly on a role-based, least-privilege basis. Employees handling Restricted data must store files exclusively on the secure corporate server drives or the approved encrypted cloud storage environment. Transferring Restricted data to personal external hard drives, unauthorized USB flash drives, or personal email accounts is strictly prohibited and will trigger automated IT alerts. All email transmissions containing Restricted data to approved external partners must utilize the company secure email encryption tool. Employees are required to lock their computer screens when leaving their desks and must properly shred all physical documents containing Internal or Restricted data using the designated secure disposal bins located in the printing areas.""",

    "vpn-access-policy.txt": """EnterpriseCorp VPN Access Policy
The EnterpriseCorp Virtual Private Network allows authorized remote users to securely access the internal corporate network and private servers. All remote work must be conducted through the official VPN client when accessing internal databases, the intranet, or staging environments. VPN access is provisioned automatically for full-time employees upon completion of IT onboarding. Contractors and temporary staff must submit a formal access request, approved by a Department Director, specifying the exact duration and scope of required access. The VPN client enforces a strict idle timeout; connections will be automatically severed after 30 minutes of inactivity, requiring the user to re-authenticate using Multi-Factor Authentication. Split-tunneling is disabled by default, ensuring all remote traffic is routed through the company central security firewalls and content filters. Employees must not share their VPN credentials or allow non-employees to utilize their active connection. Connecting to the VPN via unsecured, public Wi-Fi networks found in coffee shops or airports is prohibited unless the employee is concurrently utilizing the IT-approved secondary encryption wrapper. Any detected anomalous login locations or simultaneous geographic logins will result in immediate automated suspension of the user VPN privileges pending IT review.""",

    "software-installation-policy.txt": """EnterpriseCorp Software Installation Policy
To maintain system stability and prevent the introduction of malware, employees are prohibited from downloading or installing unauthorized software on EnterpriseCorp hardware. All endpoints operate with standard user privileges, meaning administrative rights required for software installation are locked. A pre-approved catalog of productivity, development, and design applications is available in the EnterpriseCorp Self-Service Software Center. Employees may install any application from this catalog without additional approval. For software not listed in the catalog, employees must submit a Software Request Ticket to the IT Service Desk. The request must include the business justification, the specific software version, and the licensing cost. IT Security requires up to 5 business days to evaluate the requested software for vulnerabilities, compliance with data privacy regulations, and system compatibility. If approved, an IT technician will remotely deploy the software to the user device. Employees attempting to bypass installation restrictions using portable executable files or unverified browser extensions will be flagged by endpoint detection systems, resulting in the immediate quarantine of the device and mandatory security retraining for the user.""",

    "expense-reimbursement-policy.txt": """EnterpriseCorp Expense Reimbursement Policy
EnterpriseCorp reimburses employees for reasonable and necessary expenses incurred directly in the course of approved business activities. Eligible expenses include client meals, local transit to client sites, and approved professional development materials. All expenses must be submitted through the company financial portal within 30 days of the transaction date. Reimbursement requests must include a high-resolution digital scan or photograph of the original itemized receipt; credit card summary statements are not accepted as valid proof of purchase. Client meals are capped at $75 per person, including tax and a maximum 20 percent gratuity. The names of all attendees and the specific business purpose of the meal must be documented in the submission. Expenditures exceeding $200 require documented pre-approval from the employee direct line manager prior to the purchase. The Finance department processes approved reimbursements bi-weekly, issuing payments via direct deposit to the employee designated payroll account. Expenses submitted after the 30-day window will be rejected unless accompanied by an exception waiver signed by the Department Vice President. The purchase of alcohol is strictly non-reimbursable unless explicitly pre-authorized for specific corporate-sponsored events.""",

    "corporate-travel-budget-policy.txt": """EnterpriseCorp Corporate Travel Budget Policy
This policy outlines the budgeting and booking guidelines for all domestic and international business travel. All travel must be booked exclusively through the EnterpriseCorp designated travel management platform. Flights must be booked at least 14 days in advance to secure optimal pricing. Economy class is mandatory for all domestic flights and international flights with a total duration of under 8 hours. Business class travel is permitted only for continuous international flights exceeding 8 hours and requires approval from the Chief Financial Officer. The maximum nightly hotel allowance is $150 for domestic travel and $250 for designated high-cost international metropolitan areas. Employees receive a fixed daily per diem for meals and incidental expenses of $65 for domestic travel and $90 for international travel. Per diems are paid in advance and do not require itemized receipt submission, but are prorated at 75 percent for the designated days of departure and return. Car rentals are permitted only when cost-effective compared to local taxis or ride-share services, and employees must decline rental agency insurance as coverage is provided under the master corporate liability policy.""",

    "procurement-and-vendor-approval-policy.txt": """EnterpriseCorp Procurement and Vendor Approval Policy
The procurement policy ensures that all goods and services purchased by EnterpriseCorp represent optimal value, quality, and compliance. Any departmental purchase under $1,000 requires only the approval of the direct Line Manager. Purchases ranging from $1,001 to $10,000 require the approval of the Department Director and the submission of at least two competitive vendor quotes. Capital expenditures or service contracts exceeding $10,000 mandate a formal Request for Proposal process, requiring a minimum of three competitive bids, followed by approval from the Chief Financial Officer and the Procurement Committee. Before engaging a new vendor, the vendor must pass a due diligence review covering financial stability, cybersecurity compliance, and legal standing, a process taking up to 10 business days. Employees are strictly forbidden from signing vendor contracts, master service agreements, or legally binding statements of work; all external contracts must be reviewed by the Legal department and signed exclusively by an authorized corporate officer. Department managers must formally review recurring vendor contracts annually 60 days prior to renewal dates to assess ongoing value and performance metrics.""",

    "corporate-credit-card-policy.txt": """EnterpriseCorp Corporate Credit Card Policy
EnterpriseCorp issues corporate credit cards to employees whose roles require frequent travel, client entertainment, or regular departmental purchasing. Corporate cards are to be used exclusively for authorized business expenditures; personal use of the corporate card is strictly prohibited, regardless of intention to reimburse the company. The standard monthly credit limit is set at $3,000 for individual contributors and $10,000 for department heads. Cardholders are entirely responsible for the security of their physical card and must immediately report lost or stolen cards to the issuing bank and the Finance department. By the 5th day of each month, cardholders must log into the expense management system to reconcile their previous month statement, allocating each transaction to the correct general ledger code and attaching itemized receipts for all transactions exceeding $25. Failure to reconcile the statement by the 10th day of the month will result in a temporary suspension of the card. A second consecutive failure to reconcile on time will result in permanent revocation of the corporate card and potential formal disciplinary action regarding financial negligence.""",

    "comprehensive-health-insurance-policy.txt": """EnterpriseCorp Comprehensive Health Insurance Policy
EnterpriseCorp provides comprehensive medical, dental, and vision insurance to all full-time employees and their eligible dependents, effective from the first day of the month following 30 days of continuous employment. The company subsidizes 85 percent of the monthly premium cost for the employee and 70 percent of the premium cost for a spouse, domestic partner, and dependent children under the age of 26. Employees may choose between a Preferred Provider Organization plan or a High Deductible Health Plan paired with a Health Savings Account. For employees opting into the High Deductible plan, the company provides an annual seed contribution of $1,000 for individuals and $2,000 for family coverage, deposited into the HSA in bi-annual installments in January and July. Open enrollment occurs annually during the month of November, during which employees may add or remove dependents or switch plan types. Outside of open enrollment, changes to coverage can only be made within 30 days of a qualifying life event, such as marriage, divorce, or the birth of a child, requiring the submission of legal documentation to the HR benefits coordinator.""",

    "employee-wellness-program-policy.txt": """EnterpriseCorp Employee Wellness Program Policy
EnterpriseCorp is committed to supporting the physical and mental well-being of its workforce through the Employee Wellness Program. All full-time and part-time employees are eligible for a monthly wellness stipend of $75. This stipend is added to the first paycheck of each month and is intended to cover expenses related to physical fitness, including gym memberships, yoga classes, fitness applications, or the purchase of home exercise equipment. No receipts are required to claim this monthly stipend. Additionally, the company provides a confidential Employee Assistance Program available 24 hours a day. The program offers up to 6 free, fully subsidized counseling sessions per calendar year per employee or immediate family member, addressing stress, anxiety, financial planning, or legal concerns. EnterpriseCorp also designates the second Friday of every quarter as a Recharge Day, which is a fully paid company-wide holiday designed to prevent burnout. Employees are strictly discouraged from sending internal emails or scheduling meetings on Recharge Days to ensure uninterrupted rest for all staff members.""",

    "retirement-and-provident-fund-policy.txt": """EnterpriseCorp Retirement and Provident Fund Policy
To assist employees in building long-term financial security, EnterpriseCorp offers a robust retirement savings program. Full-time employees are automatically enrolled in the corporate 401k or regional Provident Fund equivalent upon the completion of their 90-day probationary period. The default employee contribution rate is set at 5 percent of the employee pre-tax base salary, though employees may manually adjust this percentage or opt out entirely via the HR benefits portal. EnterpriseCorp provides a generous employer matching program, matching 100 percent of the first 4 percent of the employee contribution, and 50 percent of the next 2 percent, resulting in a maximum company match of 5 percent of the base salary. Employer matching contributions are subject to a 3-year graded vesting schedule. Employees become 33 percent vested in the company contributions after 1 year of continuous service, 66 percent vested after 2 years, and fully vested at 100 percent upon completing 3 years of service. Employee personal contributions are always 100 percent immediately vested. Administrative fees for the retirement accounts are fully subsidized by the company.""",

    "learning-and-development-stipend-policy.txt": """EnterpriseCorp Learning and Development Stipend Policy
EnterpriseCorp actively encourages continuous professional growth by providing an annual Learning and Development stipend of $1,500 to all full-time employees who have completed at least 6 months of continuous service. The stipend resets annually on January 1st and does not carry over to subsequent years. Eligible expenses include industry conferences, professional certification exams, online course subscriptions, and job-related academic textbooks. To utilize the stipend, employees must submit a proposal to their direct manager detailing the cost of the resource and its direct relevance to their current role or established career progression plan. Upon managerial approval, the employee may either request the company to pay the vendor directly via corporate card or purchase the resource personally and submit for reimbursement. If an employee resigns or is terminated for cause within 6 months of the company funding a certification or conference exceeding $500, the employee must repay 50 percent of the total cost, which will be withheld from their final paycheck. Mandatory compliance training mandated by the company does not count against the employee annual balance.""",

    "employee-referral-bonus-policy.txt": """EnterpriseCorp Employee Referral Bonus Policy
EnterpriseCorp believes our employees are the best source for identifying top-tier talent. The Employee Referral Bonus Policy rewards current staff who successfully refer candidates for open full-time positions. The standard referral bonus is $1,500 for entry-level to mid-level roles, and $3,000 for senior management or specialized engineering positions, as clearly designated on the internal job board. To be eligible, the referring employee must submit the candidate resume through the applicant tracking system referral portal before the candidate applies independently. Vice Presidents, Human Resources staff, and the hiring manager directly responsible for the open role are ineligible to receive the referral bonus. The bonus payment is structured in two equal installments: 50 percent is paid on the referred candidate first day of employment, and the remaining 50 percent is paid upon the referred candidate successful completion of their 90-day probationary period. Both the referring employee and the referred candidate must be actively employed and in good standing with EnterpriseCorp on the scheduled payout dates for the bonus to be disbursed via the standard payroll cycle.""",
}

if __name__ == "__main__":
    target_dir = "backend/rag/documents"
    os.makedirs(target_dir, exist_ok=True)

    for filename, content in DOCS.items():
        with open(os.path.join(target_dir, filename), "w", encoding="utf-8") as f:
            f.write(content.strip())

    print(f"Wrote {len(DOCS)} policy documents to {target_dir}/")